<a href="https://colab.research.google.com/github/lagos-a1/ECA-data-base/blob/master/ECA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import io
from datetime import date
from google.colab import files

In [2]:
uploaded = files.upload()
df = pd.read_csv(io.StringIO(uploaded['Format1.csv'].decode('utf-8')))

Saving Format1.csv to Format1.csv

In [3]:
BackupDF = df.copy()
df

Empty DataFrame
Columns: [SiteCode, SiteName, SubSiteName, IsSiteActive, IsSiteShared, Addr1, Addr2, Addr3, Suburb, State, PostCode, Country, PostalAddr1, PostalAddr2, PostalAddr3, PostalSuburb, PostalState, PostalPostCode, PostalCountry, WebAddress, SiteEmail, SiteAlternateEmail, Phone1, Phone2, Fax, Sector, SiteComment, PrivateSiteComment, ContactCode, ContactPosition, ContactTitle, ContactFirstName, ContactMiddleName, ContactSurname, ContactQualifications, ContactEmail, ContactAlternateEmail, ContactPhWork, ContactPhMobile, ContactGender, ContactIsPrimary, ContactIsStudentContact, ContactIsAccessibilityEnabled, SiteDescriptors, SiteAreas, SiteFocuses, SiteRegions, AgreementProvider, AgreementIssueDate, AgreementExpiryDate, LocationGroup, Location]
Index: []

In [4]:
uploaded1 = files.upload()
df1 = pd.read_csv(io.StringIO(uploaded1['Host Company.csv'].decode('utf-8')))

Saving Host Company.csv to Host Company.csv

In [19]:
df1

      CC_Id  ... Num_CompanyJobRoles
0         1  ...                   2
1         3  ...                   3
2         4  ...                   1
3         6  ...                   2
4         7  ...                   1
...     ...  ...                 ...
1942   3057  ...                   1
1943   3058  ...                   1
1944   3059  ...                   1
1945   3060  ...                   1
1946   3061  ...                   1

[1947 rows x 23 columns]

In [30]:
df1.dtypes

CC_Id                       int64
CompanyName                object
Host Company Status        object
Valid From                 object
Valid To                   object
Status                     object
DataSource                 object
Contact Person             object
PreferredContactMethod    float64
Phone1                     object
Phone2                     object
Mobile1                    object
Mobile2                    object
Email                      object
AlternateEmail             object
Supervisor                 object
Designation                object
Department                 object
Supervisor Tel             object
Supervisor Mobile          object
Supervisor Email           object
Num_SupervisorJobRoles      int64
Num_CompanyJobRoles         int64
dtype: object

In [7]:
uploaded2 = files.upload()
df2 = pd.read_csv(io.StringIO(uploaded2['datesBase.csv'].decode('utf-8')))

Saving datesBase.csv to datesBase.csv

In [8]:
df2

     CC_id  ... Check box if BD Team Needs to Follow Up
0      164  ...                                     NaN
1      252  ...                                     NaN
2        1  ...                                     NaN
3      506  ...                                     NaN
4        4  ...                                     NaN
..     ...  ...                                     ...
389   1566  ...                                     NaN
390   1122  ...                                     NaN
391   1246  ...                                     NaN
392    725  ...                                     NaN
393    155  ...                                     NaN

[394 rows x 17 columns]

In [9]:
uploaded3 = files.upload()
df3 = pd.read_csv(io.StringIO(uploaded3['Address.csv'].decode('utf-8')))

Saving Address.csv to Address.csv

In [10]:
df3

      CompanyId                         companyName  ... Postcode    country
0             1           Sydney Language Solutions  ...     2000  Australia
1             3         Forte Information Solutions  ...     2127  Australia
2             4                           GDR Group  ...     2009  Australia
3             6                    Astra Consulting  ...     3205  Australia
4             7                 Australia Bus Group  ...     3803  Australia
...         ...                                 ...  ...      ...        ...
1954       3063                        Inspire C.A.  ...     4006  Australia
1955       3064                Cloud Industry Group  ...     4000  Australia
1956       3065                The Co-Group Limited  ...     2148  Australia
1957       3066  Expert Education and Visa Services  ...     4000  Australia
1958       3067                   Redhill Education  ...     2007  Australia

[1959 rows x 7 columns]

In [0]:
def firstname (firstname):
    Nfirst = firstname.split()
    firstName = Nfirst[0]
    return firstName
  
def lastname (lastname):
    Nlast = lastname.split()
    lastname = Nlast[1]
    return lastname
  
#firstname('Laura Barandiaran')

#lastname ('Laura Barandiaran')

In [0]:
df['SiteCode']= df1['CC_Id'] 
df['SiteName']= df1['CompanyName'] 
df['Addr1'] = df1['CC_Id'].map(df3.set_index('CompanyId')['Street Address'])
df['Suburb'] = df1['CC_Id'].map(df3.set_index('CompanyId')['Suburb'])
df['State'] = df1['CC_Id'].map(df3.set_index('CompanyId')['State'])
df['PostCode'] = df1['CC_Id'].map(df3.set_index('CompanyId')['Postcode'])
df['Country'] = df1['CC_Id'].map(df3.set_index('CompanyId')['country'])
df['ContactPosition'] = df1['CC_Id'].map(df1.set_index('CC_Id')['Designation'])
df['ContactFirstName'] = df1['Supervisor'].apply(lambda x: x.split(' ')[0])
df['ContactSurname'] = df1['Supervisor'].apply(lambda x: x.split(' ')[1])
df['ContactEmail'] = df1['CC_Id'].map(df1.set_index('CC_Id')['Email'])

In [28]:
df

      SiteCode  ... Location
0            1  ...      NaN
1            3  ...      NaN
2            4  ...      NaN
3            6  ...      NaN
4            7  ...      NaN
...        ...  ...      ...
1942      3057  ...      NaN
1943      3058  ...      NaN
1944      3059  ...      NaN
1945      3060  ...      NaN
1946      3061  ...      NaN

[1947 rows x 52 columns]

In [24]:
fullname = "Linus Torvalds"
fullname.split(" ")

['Linus', 'Torvalds']

In [18]:
df1.dtypes

CC_Id                       int64
CompanyName                object
Host Company Status        object
Valid From                 object
Valid To                   object
Status                     object
DataSource                 object
Contact Person             object
PreferredContactMethod    float64
Phone1                     object
Phone2                     object
Mobile1                    object
Mobile2                    object
Email                      object
AlternateEmail             object
Supervisor                 object
Designation                object
Department                 object
Supervisor Tel             object
Supervisor Mobile          object
Supervisor Email           object
Num_SupervisorJobRoles      int64
Num_CompanyJobRoles         int64
dtype: object

In [17]:
def get_digit(number, n):
    x = number // 10**n % 10
    return x
get_digit(987654321, 0)
# 1

get_digit(987654321, 5)
# 6

6